base:
  algorithm: DB
  save_dir: saved
  gpu_id: 0,1
  ckpt_file: checkpoint/model_best.pth
dataset:
  type: CTW1500
  crop_shape: [736, 736]
  train_load:
    train_img_dir: 'dataset/CTW1500/train/img'
    train_label_dir: 'dataset/CTW1500/train/gt'
    batch_size: 4
    num_workers: 4
  test_load:
    test_img_dir: 'dataset/CTW1500/test/img'
    test_label_dir: 'dataset/CTW1500/test/gt'
    batch_size: 1
    num_workers: 4
  function: src.loader.detection.det_loader,DetLoader
model:
  backbone:
    pretrained: False
    function: src.model.common.resnet_dcn,resnet50
  head:
    in_channels: [256, 512, 1024, 2048]
    inner_channels: 256
    function: src.model.detection.head,DBHead
  segout:
    inner_channels: 256
    k: 50
    adaptive: True
    function: src.model.detection.segout,SegDetector
  function: src.model.detection.db_net,DBNet
loss:
  function: src.model.loss,DBLoss
  l1_scale: 1
  bce_scale: 10
optimizer:
  base_lr: 0.007
  weight_decay: 0.0001
  momentum: 0.9
  function: src.model.optimizer,SGDDecay
scheduler:
  factor: 0.9
post_process:
  thresh: 0.3
  box_thresh: 0.5
  max_candidates: 1000
  is_poly: False
  unclip_ratio: 1.5
  min_size: 3
  function: src.model.detection.postprocess,DBPostProcess

