base:
  algorithm: DBnet
  crop_shape: [640, 640]
  pretrained: True
  in_channels: [256, 512, 1024, 2048]
  inner_channels: 256
  k: 50
  n_epoch: 600
  epoch_val: 50
  show_step: 100
  adaptive: True
  checkpoint: 'checkpoint'
  gpu_id: 0,1
  restore: False
  restore_file: 'checkpoint/current.pth'
  dataset: ICDAR
train_load:
  function: src.loader.det_loader,DBLoaderTrain
  train_img_dir: '/data/cuongnm1/dataset/icdar/train/img'
  train_label_dir: '/data/cuongnm1/dataset/icdar/train/gt'
  batch_size: 8
  num_workers: 4
val_load:
  function: src.loader.det_loader,DBLoaderTest
  val_img_dir: '/data/cuongnm1/dataset/icdar/test/img'
  val_label_dir: '/data/cuongnm1/dataset/icdar/test/gt'
  batch_size: 1
  num_workers: 4
  test_size: 736
  stride: 32
model:
  function: src.model.det_model.db_net,DBNet
  loss_function: src.model.det_model,DetLoss
  backbone: src.model.backbone.resnet,resnet50
  head: src.model.det_model.head,DBHead
  segout: src.model.det_model.segout,SegDetector
loss:
  function: src.model.loss,DBLoss
  l1_scale: 1
  bce_scale: 10
optimizer:
  function: src.model.optimizer,SGDDecay
  base_lr: 0.002
  weight_decay: 0.0005
  momentum: 0.95
optimizer_decay:
  function: src.model.optimizer,adjust_learning_rate_poly
  factor: 0.9
postprocess:
  function: src.model.det_model.postprocess,DBPostProcess
  thresh: 0.3
  box_thresh: 0.5
  max_candidates: 1000
  is_poly: False
  unclip_ratio: 1.5
  min_size: 3
infer:
  model_path: 'checkpoint/DBnet_best.pth'
  img_path: 'dataset/test/1.jpg'
  result_path: 'dataset/result'
