base:
  althgorithm: DBnet
  crop_shape: [640, 640]
  pretrained: False
  in_channels: [256, 512, 1024, 20248]
  inner_channels: 256
  k: 50
  n_epoch: 600
  show_step: 100
  adaptive: True
  checkpoint: 'checkpoint/model_best.pth'
  gpu_id: 0,1
  restore: False
  restore_file: 'checkpoint/current.pth'
train_load:
  function: src.loader.det_loader,DBLoaderTrain
  train_img_dir: 'dataset/CTW1500/train/img'
  train_label_dir: 'dataset/CTW1500/train/gt'
  batch_size: 8
  num_workers: 4
val_load:
  function: src.loader.det_loader,DBLoaderTrain
  val_img_dir: 'dataset/CTW1500/val/img'
  val_label_dir: 'dataset/CTW1500/val/gt'
  batch_size: 8
  num_workers: 4
model:
  function: src.model.det_model,DBNet
  backbone: src.model.backbone,resnet50
  head: src.model.head,DBHead
  segout: src.model.segout,SegDetector
loss:
  function: src.model.loss,DBLoss
  l1_scale: 1
  bce_scale: 10
optimizer:
  function: src.model.optimizer,SGD
  base_lr: 0.001
  weight_decay: 0.0005
  momentum: 0.95
optimizer_decay:
  function: src.model.optimizer,adjust_lr_poly
  factor: 0.9
possprocess:
  function: src.model.possprocess,DBPossprocess
  thresh: 0.3
  box_thresh: 0.5
  max_candidates: 1000
  is_poly: False
  unclip_ratio: 1.5

