dataset:
  img_w: 256
  img_h: 32
  case_sensitive: False
  to_gray: False
  transform: None
  target_transform: None
  txt_file: '/data/cuongnm1/dataset/..'
  img_root: '/data/cuongnm1/dataset/..'
model_arch:
  gcb:
    in_channels: 32
    ratio: 0.0625
    headers: 8
    pooling_type: 'att'
    att_scale: True
    fusion_type: 'channel_concat'
  backbone:
    use_gcb: [False, True, True, True]
  common:
    with_encoder: False
    tgt_vocab: 36
    d_model: 512
    nhead: 8
  encoder:
    num_layer: 3
    dropout: 0.2
    ff_dim: 2048
    share_parameter: False
  decoder:
    num_layer: 3
    dropout: 0.2
    ff_dim: 2048
    share_parameter: False
functional:
  conv_embedding_gc: src.model.backbone.resnet,ConvEmbeddingGC
  encoder: src.model.reg_model.transformer,Encoder
  decoder: src.model.reg_model.transformer,Decoder
  generator: src.model.reg_model.master,Generator
  master: src.model.reg_model.master,MASTER
