dataset:
  img_w: 256
  img_h: 32
  case_sensitive: False
  to_gray: False
  transform: 'Resize'
  target_transform: None
  train_txt_file: '/data/cuongnm1/dataset/..'
  val_txt_file: 'data/cuongnm1/dataset/..'
  img_root: '/data/cuongnm1/dataset/..'
model_arch:
  gcb:
    in_channels: 32
    ratio: 0.0625
    headers: 8
    pooling_type: 'att'
    att_scale: True
    fusion_type: 'channel_concat'
  backbone:
    use_gcb: [False, True, True, True]
  common:
    with_encoder: False
    tgt_vocab: 36
    d_model: 512
    nhead: 8
  encoder:
    num_layer: 3
    dropout: 0.2
    ff_dim: 2048
    share_parameter: False
  decoder:
    num_layer: 3
    dropout: 0.2
    ff_dim: 2048
    share_parameter: False
functional:
  load_data: src.loader.reg_loader,TextDataset
  conv_embedding_gc: src.model.backbone.resnet,ConvEmbeddingGC
  encoder: src.model.reg_model.transformer,Encoder
  decoder: src.model.reg_model.transformer,Decoder
  generator: src.model.reg_model.master,Generator
  master: src.model.reg_model.master,MASTER
train_loader:
  batch_size: 32
  shuffle: True
  drop_last: True
  num_workers: 8
val_loader:
  batch_size: 32
  shuffle: False
  drop_last: False
  num_workers: -1
optimizer:
  type: 'Adam'
  functional: src.model.optimizer,Adam
  lr: 0.0004
lr_scheduler:
  type: 'StepLR'
  step_size: 30
  gamma: 0.1
trainer:
  epochs: 100
  do_validation: True
  validation_epoch: 10
  log_step_interval: 1
  val_step_interval: 2000
  save_dir: 'saved'
  monitor: 'max_word_acc'
  distributed: True
  local_world_size: 4
  local_rank: -1
  global_rank: -1
  early_stop: -1
  resume: False
  resume_path: ''

